/**
 * SEO Utilities
 * Helper functions for metadata generation and SEO optimization
 *
 * Security: JSON-LD is sanitized to prevent XSS attacks
 * @see https://nextjs.org/docs/app/guides/json-ld
 */

import type { Metadata } from 'next';
import type { Organization, WebPage, WebSite, WithContext } from 'schema-dts';

import { siteConfig } from '@/config/site';

/**
 * Standard image sizes for different contexts
 * Following platform-specific recommendations
 */
export const IMAGE_SIZES = {
  // Open Graph (Facebook, LinkedIn) - 1.91:1 ratio
  og: {
    width: 1200,
    height: 630,
  },
  // Twitter card - 2:1 ratio
  twitter: {
    width: 1200,
    height: 600,
  },
  // Hero images - 16:9 ratio
  hero: {
    width: 1920,
    height: 1080,
  },
  // Portfolio/work thumbnails - 4:3 ratio
  thumbnail: {
    width: 800,
    height: 600,
  },
  // Avatar/profile - 1:1 ratio
  avatar: {
    width: 400,
    height: 400,
  },
} as const;

/**
 * Generate absolute URL from relative path
 */
export function absoluteUrl(path: string): string {
  return `${siteConfig.url}${path.startsWith('/') ? path : `/${path}`}`;
}

/**
 * Sanitize JSON-LD to prevent XSS attacks
 * Replaces < with unicode equivalent to prevent script injection
 *
 * @see https://nextjs.org/docs/app/guides/json-ld
 */
export function sanitizeJsonLd<T>(data: T): string {
  return JSON.stringify(data).replace(/</g, '\\u003c');
}

/**
 * Generate page metadata with proper defaults
 * Use this in page components for consistent metadata
 *
 * @example
 * export const metadata = generatePageMetadata({
 *   title: 'About Us',
 *   description: 'Learn about our team and mission',
 * });
 */
export function generatePageMetadata({
  title,
  description,
  image,
  noIndex = false,
  pathname = '',
}: {
  title: string;
  description?: string;
  image?: string;
  noIndex?: boolean;
  pathname?: string;
}): Metadata {
  const pageDescription = description ?? siteConfig.description;
  const pageUrl = absoluteUrl(pathname);

  // Base metadata - images are auto-generated by Next.js
  const metadata: Metadata = {
    title,
    description: pageDescription,
    openGraph: {
      title,
      description: pageDescription,
      url: pageUrl,
    },
    twitter: {
      title,
      description: pageDescription,
    },
    alternates: {
      canonical: pageUrl,
    },
  };

  // Add custom image if provided
  if (image) {
    metadata.openGraph = {
      ...metadata.openGraph,
      images: [
        {
          url: image,
          width: IMAGE_SIZES.og.width,
          height: IMAGE_SIZES.og.height,
          alt: title,
        },
      ],
    };
    metadata.twitter = {
      ...metadata.twitter,
      images: [image],
    };
  }

  // Add noIndex if specified
  if (noIndex) {
    metadata.robots = {
      index: false,
      follow: false,
    };
  }

  return metadata;
}

/**
 * Generate JSON-LD structured data for organization
 * Helps search engines understand the business
 *
 * Type-safe using schema-dts
 */
export function generateOrganizationSchema(): WithContext<Organization> {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: siteConfig.name,
    description: siteConfig.description,
    url: siteConfig.url,
    logo: absoluteUrl('/logo.png'),
    founder: {
      '@type': 'Person',
      name: siteConfig.founder,
    },
    foundingDate: '2025',
    address: {
      '@type': 'PostalAddress',
      addressLocality: siteConfig.location?.city,
      addressRegion: siteConfig.location?.state,
      addressCountry: siteConfig.location?.country,
    },
    sameAs: [
      siteConfig.links.linkedin,
      siteConfig.links.github,
    ],
    contactPoint: {
      '@type': 'ContactPoint',
      email: siteConfig.email,
      telephone: siteConfig.phone,
      contactType: 'customer service',
      availableLanguage: ['English', 'Hindi'],
    },
  };
}

/**
 * Generate JSON-LD structured data for the website
 */
export function generateWebSiteSchema(): WithContext<WebSite> {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: siteConfig.name,
    description: siteConfig.description,
    url: siteConfig.url,
  };
}

/**
 * Generate JSON-LD structured data for a web page
 */
export function generateWebPageSchema({
  title,
  description,
  pathname = '',
}: {
  title: string;
  description: string;
  pathname?: string;
}): WithContext<WebPage> {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: title,
    description,
    url: absoluteUrl(pathname),
    isPartOf: {
      '@type': 'WebSite',
      name: siteConfig.name,
      url: siteConfig.url,
    },
  };
}

/**
 * Generate JSON-LD structured data for services
 */
export function generateServiceSchema({
  name,
  description,
  pathname,
}: {
  name: string;
  description: string;
  pathname: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Service',
    name,
    description,
    provider: {
      '@type': 'Organization',
      name: siteConfig.name,
      url: siteConfig.url,
    },
    url: absoluteUrl(pathname),
  };
}
